### ISSUE TITLE
wiki controller is singular and should be plural. 

### ISSUE THREAD

**Issue by hartly97** [Panga123/blocipedia#6]
https://github.com/Panga123/blocipedia/blob/1218e671503d79f8be7167185f219920080270b0/app/controllers/wiki_controller.rb#L1

app/controllers/wikis_controller.rb

**Comment by Panga123** [comment]
If I do this, what other wiki mentions would I have to update to wikis? Is this something I can just do a fine and replace all on? I'm afraid I messed up the plural/singular in various spots.
